"use strict";

exports.getItems = () => {
  return {
    dev: {
      "abc-a1": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25051,
        ip2: "?.?.?.?",
        port2: 22,
        role: "app",
        apps: [],
      },
      "abc-d1": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25052,
        ip2: "?.?.?.?",
        port2: 22,
        role: "db",
        apps: [],
      },
    },
    stg: {
      "abc-a2": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25053,
        ip2: "?.?.?.?",
        port2: 22,
        role: "app",
        apps: [],
      },
      "abc-d2": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25054,
        ip2: "?.?.?.?",
        port2: 22,
        role: "db",
        pps: [],
      },
    },
    ops: {
      "abc-p1": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 22,
        ip2: "?.?.?.?",
        port2: 22,
        role: "proxy",
        pps: [],
      },
      "abc-a3": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25055,
        ip2: "?.?.?.?",
        port2: 22,
        role: "app",
        apps: [],
      },
      "abc-a4": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25056,
        ip2: "?.?.?.?",
        port2: 22,
        role: "app",
        apps: [],
      },
      "abc-d3": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25057,
        ip2: "?.?.?.?",
        port2: 22,
        role: "db",
        pps: [],
      },
      "abc-d4": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25058,
        ip2: "?.?.?.?",
        port2: 22,
        role: "db",
        pps: [],
      },
      "abc-d5": {
        use: true,
        cloud: true,
        ip: "?.?.?.?",
        port: 25059,
        ip2: "?.?.?.?",
        port2: 22,
        role: "db",
        pps: [],
      },
    },
  };
};
